### ISSUE TITLE
Angle brackets in place of square brackets

### ISSUE THREAD

**Issue by ghost** [oh-my-fish/theme-chain#4]
My prompt looks different from the screenshot on the repo. Here, links are enclosed in angle brackets (< and >) instead of square brackets ([ and ]). I tried reading chain functions code but there is no mention of these characters anywhere.

![screen shot 2017-09-26 at 10 59 33 am](https://user-images.githubusercontent.com/903339/30875930-d44ad0bc-a2a9-11e7-9eae-3289a0976a7a.png)

**Comment by sagebind** [comment]
The screenshot was taken before #2 was merged in, in which changing square brackets to angle brackets was just a small part of the large changes. Ideally the screenshot and animated preview should be updated.

The bracket characters are not currently customizable, but they certainly could be. The source code for chain is admittedly a little hard to understand -- the way chain works is that it "compiles" a new function on shell startup containing optimized print calls for each part of the prompt; that's why it is so snappy afterward. The function that does the compiling is in `chain.compile.fish`, and you can see in there the angle brackets are hard-coded.

**Comment by NelsonBlakeN** [comment]
I'm a little late, but have the same question. Is this to say that in order to customize these characters, one would have to fork the code, edit `chain.compile.fish` manually, then run the forked version instead?
